apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-pull-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: registry-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ha-pvt.t0xe7uh231qhhb7.itbg.svc40.mycloudplatform.cloud": {
                "username": "{{ .USERNAME }}",
                "password": "{{ .PASSWORD }}",
                "auth": "{{ printf "%s:%s" .USERNAME .PASSWORD | b64enc }}"
              }
            }
          }
  data:
    - secretKey: USERNAME
      remoteRef:
        key: app/registry
        property: USERNAME
    - secretKey: PASSWORD
      remoteRef:
        key: app/registry
        property: PASSWORD
