name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'build/kaas/**'

env:
  DOCKER_REGISTRY: ha-pvt.t0xe7uh231qhhb7.itbg.svc40.mycloudplatform.cloud
  IMAGE_NAME: devsecops/demo2025-kaas
  IMAGE_TAG: 0.0.5

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: echo $DOCKER_PASSWORD | docker login ${{ env.DOCKER_REGISTRY }} -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} build/kaas
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
